<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::table('blogs', function (Blueprint $table) {

            // Drop old unique index (name generated by Laravel)
            $table->dropUnique('blogs_slug_unique');

            // Add new composite unique rule
            $table->unique(['slug', 'deleted_at'], 'blogs_slug_deleted_at_unique');
        });
    }

    public function down()
    {
        Schema::table('blogs', function (Blueprint $table) {

            // Drop composite unique index
            $table->dropUnique('blogs_slug_deleted_at_unique');

            // Restore old unique index
            $table->unique('slug', 'blogs_slug_unique');
        });
    }
};
